base: 'http://production.bioinf.kwmhgb.at/'
languages:
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /
    websiteTitle: ''
    navigationTitle: English
    flag: us
    languageId: 0
rootPageId: 1
websiteTitle: Bioinformatics
